on:
  push:
    branches: [app]
    paths-ignore:
    - '.github/**'

name: climrapp

jobs:
  climr:
  runs-on: self-hosted
  steps:
    - uses: actions/checkout@main
    - run: |
        rm -R /srv/shiny-server/climr-app
        cp -R ../climr-app /srv/shiny-server/
        touch /srv/shiny-server/climr-app/restart.txt